[tool.black]
line-length = 79
skip-string-normalization = true

[tool.isort]
line_length = 79

[tool.flake8]
max-line-length = 79
extend-ignore = "E203, W503"
exclude = [
    ".git",
    "__pycache__",
    ".venv"
]
