[tool.black]
line-length = 90
target-version = ['py38']

[tool.isort]
line_length = 90
multi_line_output = 4
use_parentheses = true
include_trailing_comma = true
ensure_newline_before_comments = true
known_third_party = ["concurrent", "multiprocessing", "time"]
